version: "3"

networks:
    public:
        driver: bridge
    internal:
        driver: bridge
        internal: true

services:
#    polnpy_front:
#        image: apache
#        ports:
#            - 80:80

    polnpy_api:
        image: matthieu88160/polnpy
        # build: ../../image/php7.2-apache
        ports:
            - 81:80
        networks:
            - internal
            - public
        depends_on:
            - mongo
    
    mongo:
        image: matthieu88160/polnpymongo
        # image: mongo
        networks:
            - internal

    redis:
        image: redis
        networks:
            - internal
